// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV--t4UFpLGnMzt4p58xOHdFevyK_ttys',
    appId: '1:1015755971591:web:b549c52db3676679d4dea2',
    messagingSenderId: '1015755971591',
    projectId: 'katy-acac7',
    authDomain: 'katy-acac7.firebaseapp.com',
    databaseURL: 'https://katy-acac7-default-rtdb.firebaseio.com',
    storageBucket: 'katy-acac7.firebasestorage.app',
    measurementId: 'G-ZDDVMLQHP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTnutbvR7JhRDzIGUR-warx0gD_21503Y',
    appId: '1:1015755971591:android:a103d97c87977abed4dea2',
    messagingSenderId: '1015755971591',
    projectId: 'katy-acac7',
    databaseURL: 'https://katy-acac7-default-rtdb.firebaseio.com',
    storageBucket: 'katy-acac7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdr5of9Yql7D74VuKM5or0HIEqjbXQWrM',
    appId: '1:1015755971591:ios:ee86da6615e66248d4dea2',
    messagingSenderId: '1015755971591',
    projectId: 'katy-acac7',
    databaseURL: 'https://katy-acac7-default-rtdb.firebaseio.com',
    storageBucket: 'katy-acac7.firebasestorage.app',
    iosBundleId: 'com.example.katy',
  );
}
